/** Rebuild after publishing audio assets. Never re-extract or overwrite MP3s. */
import { readdir } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const files = (
  await readdir(`${root}/apps/electrobun/public/assets/sound/effects`)
)
  .filter((name) => name.endsWith(".mp3"))
  .sort();
await Bun.write(
  `${root}/apps/electrobun/src/game/audio/effect-files.ts`,
  `// Generated by scripts/generate-audio-catalog.ts from published MP3s.\nexport const EFFECT_FILES: readonly string[] = [\n${files.map((file) => `  ${JSON.stringify(file)},`).join("\n")}\n];\n`
);
console.log(`Indexed ${files.length} effects`);
